name: Publish to GitHub pages

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Cache Python
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('.github/mkdocs/requirements.txt') }}
          
      - name: Setup Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.x'
      
      - name: Prepare MkDocs build
        run: bash .github/scripts/prepare_publish.sh
      
      - name: Publish MkDocs
        run: mkdocs gh-deploy
