name: Publish to GitHub pages

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docs
        uses: athackst/mkdocs-simple-plugin@v2.3.0
        with:
          publish_branch: gh-pages
          config: "mkdocs.yml"
          push: 1
