name: Run fix_abs_path.sh on push to unstable

on:
  push:
    branches:
      - unstable

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set all md filesystem paths as absolute (starting with /)
        run: bash .github/scripts/set_abs_path.sh

